### ISSUE TITLE
[回報] Weekly-mission 失效

### ISSUE THREAD

**Issue by LostSunset** [wdzeng/pinkoi-coins-bot#5]
Ver.1.2.0
weekly mission 由於有改版，目前任務需到app內領獎。
Docker執行後出現error如下圖。
![image](https://user-images.githubusercontent.com/51314629/186795756-cd455979-ba45-4a66-9a0e-f3266d36d836.png)

**Comment by wdzeng** [comment]
> Ver.1.2.0 weekly mission 由於有改版，目前任務需到app內領獎。 Docker執行後出現error如下圖。 ![image](https://user-images.githubusercontent.com/51314629/186795756-cd455979-ba45-4a66-9a0e-f3266d36d836.png)

感謝回報!! 下班後馬上修

這東西居然有人用🥺🥺

**Comment by LostSunset** [comment]
感謝作者大大的用心，好東西肯定要用的XDD。
pinkoi加上您的蝦皮bot，現在docker搭配cron實現每日自動簽到中。
正在看您的開源，想辦法看看能不能讓麥當勞app也自動簽到和解任務。

**Comment by wdzeng** [comment]
Hi @LostSunset,

非常感謝你的回報！請試試看 1.3.0 的 image。

**Comment by LostSunset** [comment]
謝謝您 ！有任何問題會再回報給您 🙏
