### ISSUE TITLE
[回報]12/5 聖誕任務更新，功能失效

### ISSUE THREAD

**Issue by LostSunset** [wdzeng/pinkoi-coins-bot#8]
Hi 作者大人 :
Pinkoi更新聖誕周間任務，如下圖。
![image](https://user-images.githubusercontent.com/51314629/205543468-100f5920-88cb-4d68-b4ba-ec9d0800704e.png)

失效 : 
![image](https://user-images.githubusercontent.com/51314629/205543560-954d45e5-b688-49fa-8af2-fca598ebf6e2.png)

想請問有沒有方法在失效時自己改coding，這樣就不用一直麻煩您更新。

**Comment by wdzeng** [comment]
抱歉久等了，這陣子在當兵。

**Comment by LostSunset** [comment]
沒問題的作者大大，等您凱旋歸來。

**Comment by wdzeng** [comment]
嗨，抱歉實在久等了。最近有比較多空餘的時間，我會開始更新把機器人更新。

Pinkoi 的聖誕任務已經 outdate 了，然後又來了一些更難解的新任務。更新可能會需要一些時間。

**Comment by LostSunset** [comment]
阿，不好意思，沒有及時回覆您，謝謝您抽空更新!
您的Docker bot真的實用，搭配Linux可以做到每日簽到，愛不釋手 XD

**Comment by wdzeng** [comment]
已發布 v1.4.0，再請你試試看。實在抱歉拖了這麼久。

**Comment by LostSunset** [comment]
Hi 作者大大，
抱歉回覆晚了，經測試已經可以正常使用，非常謝謝您 ! orz
